### PR TITLE
Tutorial

### PR DESCRIPTION
**Pull request by Tehsurfer**
An interactive tutorial which can be used to direct users through the site on their first visit.

### CODE REVIEW

**Comment by Tehsurfer** [comment]
**Note: 
Since the tutorial is an overlay across the whole site on first visit, all cypress tests will fail until we disable the tutorial for cypress (or alternatively click through the tutorial with cypress)

**Comment by alan-wu** [comment]
> **Note:
> Since the tutorial is an overlay across the whole site on first visit, all cypress tests will fail until we disable the tutorial for cypress (or alternatively click through the tutorial with cypress)

The tutorial is part of the webapp so it is important to have it tested as well. You are welcome to add some testing for the tutorial.

**Comment by alan-wu** [comment]
Can you undo the change on api/api,py please? I cant leave comment there as the files changed does not show any change you made in the force push. Thanks.

**Comment by Tehsurfer** [comment]
> Can you undo the change on api/api,py please? I cant leave comment there as the files changed does not show any change you made in the force push. Thanks.

As far as I can tell, the branch `tutorial` which I pushed from, [hasn't had any changes since July.](https://github.com/Tehsurfer/data-portal/blob/tutorial/api/api.py) 

Also if we check the [changed files](https://github.com/ABI-Software/data-portal/pull/63/files) , api/api.py has no changes.

**Comment by alan-wu** [comment]
> > Can you undo the change on api/api,py please? I cant leave comment there as the files changed does not show any change you made in the force push. Thanks.
> 
> As far as I can tell, the branch `tutorial` which I pushed from, [hasn't had any changes since July.](https://github.com/Tehsurfer/data-portal/blob/tutorial/api/api.py)
> 
> Also if we check the [changed files](https://github.com/ABI-Software/data-portal/pull/63/files) , api/api.py has no changes.

Ya, I got confused with some of the changeset which I managed to click onto from this page.

**Comment by alan-wu** [comment]
There is a bug with the exit button. Instead of exiting the tutorial, it goes back to previous tutorial and it also fails to remove the gray out area if "Next" is clicked before clicking on Exit till the tutorial is gone.

**Comment by alan-wu** [comment]
May I also suggest renaming the button from "Exit" to "Skip"?

**Comment by Tehsurfer** [comment]
> There is a bug with the exit button.

Thanks for spotting this, just fixed it with an update to @tehsurfer/chariot-tooltips

**Pull request merged**
